# based on the list from https://github.com/phillipp/spam_email
$domain_black_list = %w(
mailinator.com
trbvm.com
0-mail.com
0815.ru
0clickemail.com
00minutemail.com
10minutemail.com
20minutemail.com
2prong.com
30minutemail.com
3d-painting.com
4warding.com
4warding.net
4warding.org
60minutemail.com
amilegit.com
anonbox.net
anonymbox.com
antispam.de
beefmilk.com
binkmail.com
bio-muesli.net
bobmail.info
bofthew.com
bootybay.de
brefmail.com
bsnow.net
bugmenot.com
bumpymail.com
cosmorph.com
courrieltemporaire.com
cubiclink.com
curryworld.de
cust.in
dacoolest.com
dandikmail.com
dayrep.com
deadaddress.com
despam.it
devnullmail.com
discardmail.com
discardmail.de
disposemail.com
dispostable.com
dodgeit.com
dodgit.com
dodgit.org
doiea.com
donemail.ru
dontreg.com
dontsendmespam.de
drdrb.net
dump-email.info
dumpyemail.com
e4ward.com
email60.com
emailigo.de
emailinfive.com
emailmiser.com
emailsensei.com
emailtemporario.com.br
emailwarden.com
emailx.at.hm
evopo.com
fakeinbox.com
fakeinformation.com
fastacura.com
filzmail.com
fizmail.com
fr33mail.info
get1mail.com
get2mail.fr
getonemail.com
getonemail.net
gishpuppy.com
great-host.in
guerillamail.com
guerrillamail.com
guerrillamail.biz
guerrillamail.org
guerrillamail.net
guerrillamail.de
guerrillamailblock.com
sharklasers.com
grr.la
spam4.me
h.mintemail.com
haltospam.com
hochsitze.com
hotpop.com
hulapla.de
ieatspam.eu
ieatspam.info
ieh-mail.de
imails.info
incognitomail.com
incognitomail.net
incognitomail.org
insorg-mail.info
ipoo.org
jetable.com
jetable.net
jetable.org
jnxjn.com
junk1e.com
keepmymail.com
kir.ch.tc
klzlk.com
kulturbetrieb.info
lhsdv.com
litedrop.com
lol.ovpn.to
lookugly.com
lopl.co.cc
m4ilweb.info
mail-temporaire.fr
mail.by
mail4trash.com
mailcatch.com
maileater.com
mailexpire.com
mailimate.com
mailin8r.com
mailinator.net
mailinator2.com
mailismagic.com
mailmate.com
mailme.ir
mailme.lv
mailmetrash.com
mailnator.com
mailnesia.com
mailnull.com
mailslite.com
mailtemp.info
mailzilla.org
mbx.cc
meltmail.com
messagebeamer.de
mierdamail.com
mintemail.com
moburl.com
monemail.fr.nf
msa.minsmail.com
mt2009.com
mypartyclip.de
myphantomemail.com
mytrashmail.com
nepwk.com
no-spam.ws
nobulk.com
noclickemail.com
nogmailspam.info
nomail2me.com
nomorespamemails.com
nospam4.us
nospamfor.us
nospamthanks.info
notmailinator.com
nowmymail.com
nus.edu.sg
nwldx.com
onewaymail.com
online.ms
opayq.com
ovpn.to
owlpic.com
pjjkp.com
plexolan.de
politikerclub.de
pookmail.com
prtnx.com
qq.com
quickinbox.com
recode.me
regbypass.com
rmqkr.net
rppkn.com
rtrtr.com
s0ny.net
safe-mail.net
safetymail.info
safetypost.de
sandelf.de
saynotospams.com
selfdestructingmail.com
sendspamhere.com
shitmail.me
skeefmail.com
slopsbox.com
smellfear.com
snakemail.com
sofimail.com
sofort-mail.de
sogetthis.com
soisz.com
spam.la
spam.su
spamavert.com
spambob.net
spambob.org
spambog.com
spambog.de
spambog.net
spambog.ru
spambox.info
spambox.irishspringrealty.com
spambox.us
spamcero.com
spamday.com
spamfree24.com
spamfree24.de
spamfree24.eu
spamfree24.info
spamfree24.net
spamfree24.org
spamgourmet.com
spamherelots.com
spamhole.com
spamify.com
spaminator.de
spamkill.info
spaml.com
spaml.de
spammotel.com
spamobox.com
spamspot.com
spamthis.co.uk
spamthisplease.com
supergreatmail.com
supermailer.jp
suremail.info
teewars.org
teleworm.com
teleworm.us
tempalias.com
tempe-mail.com
tempemail.biz
tempemail.com
tempemail.net
tempinbox.co.uk
tempinbox.com
tempmail.it
tempmail2.com
tempomail.fr
temporarioemail.com.br
temporaryemail.net
temporaryinbox.com
thanksnospam.info
thankyou2010.com
thisisnotmyrealemail.com
throwawayemailaddress.com
tmailinator.com
toiea.com
tradermail.info
trash-amil.com
trash-mail.com
trash-mail.de
trash2009.com
trashemail.de
trashmail.at
trashmail.com
trashmail.net
trashmail.ws
trashmailer.com
trashymail.com
trashymail.net
trillianpro.com
tyldd.com
uggsrock.com
veryrealemail.com
webm4il.info
wegwerfemail.de
wh4f.org
whyspam.me
willselfdestruct.com
wuzupmail.net
yopmail.com
yuurok.com
zehnminutenmail.de
zippymail.info
zoaxe.com
dropmail.me
maildrop.cc
my10minutemail.com
my20minutemail.com
my00minutemail.com
15min.tk
re-gister.com
trash-me.com
you-spam.com
fake-box.com
opentrash.com
DingBone.com
FudgeRub.com
walkmail.net
lackmail.net
alivance.com
moakt.com
tmail.ws
20mail.it
0wnd.net
0wnd.org
10mail.org
10minutemail.co.uk
10minutemail.eu
10minutemail.info
10minutemail.net
10minutemail.org
10minutemail.us
33mail.com
675hosting.com
675hosting.net
675hosting.org
6paq.com
6url.com
75hosting.com
75hosting.net
75hosting.org
7tags.com
9ox.net
a-bc.net
abyssmail.com
acentri.com
afrobacon.com
ajaxapp.net
amiri.net
amiriindustries.com
anappthat.com
antichef.com
antichef.net
armyspy.com
asdasd.ru
azmeil.tk
baxomale.ht.cx
bigprofessor.so
bodhi.lawlita.com
boximail.com
broadbandninja.com
burstmail.info
casualdx.com
cbair.com
centermail.com
centermail.net
chammy.info
chogmail.com
choicemail1.com
clrmail.com
coldemail.info
cool.fr.nf
correo.blogos.net
courriel.fr.nf
crazymailing.com
cuvox.de
deadspam.com
despammed.com
dfgh.net
digitalsanctuary.com
disposableaddress.com
emailmiser.com
disposeamail.com
dm.w3internet.co.ukexample.com
drdrb.com
droplar.com
dumpandjunk.com
dumpmail.de
eelmail.com
einrot.com
emaildienst.de
emailias.com
emailto.de
emailxfer.com
emeil.in
emeil.ir
emz.net
enterto.com
ephemail.net
etranquil.com
etranquil.net
etranquil.org
explodemail.com
fastchevy.com
fastchrysler.com
fastkawasaki.com
fastmazda.com
fastmitsubishi.com
fastnissan.com
fastsubaru.com
fastsuzuki.com
fasttoyota.com
fastyamaha.com
fleckens.hu
flurred.com
frapmail.com
front14.org
fux0ringduh.com
garliclife.com
getairmail.com
ghosttexter.de
girlsundertheinfluence.com
gowikibooks.com
gowikicampus.com
gowikicars.com
gowikifilms.com
gowikigames.com
gowikimusic.com
gowikinetwork.com
gowikitravel.com
gowikitv.com
grandmamail.com
greensloth.com
gsrv.co.uk
guerillamail.biz
guerillamail.net
guerillamail.org
gustr.com
h8s.org
hatespam.org
hidemail.de
ihateyoualot.info
iheartspam.org
inbax.tk
inboxalias.com
inboxclean.com
inboxclean.org
irish2me.com
iwi.net
jetable.fr.nf
jourrapide.com
kasmail.com
kaspop.com
killmail.com
killmail.net
klassmaster.com
klassmaster.net
koszmail.pl
kurzepost.de
letthemeatspam.com
lifebyfood.com
link2mail.net
lortemail.dk
lr78.com
maboard.com
mail.mezimages.net
mail2rss.org
mail333.com
mailbidon.com
mailblocks.com
mailblog.biz
mailfa.tk
mailforspam.com
mailfreeonline.com
mailinater.com
mailincubator.com
mailmoat.com
mailshell.com
mailsiphon.com
mailspeed.ru
mailtothis.com
mailzilla.com
mega.zik.dj
meinspamschutz.de
moncourrier.fr.nf
monmail.fr.nf
monumentmail.com
mx0.wwwnew.eu
mycleaninbox.net
mypacks.net
myspaceinc.com
myspaceinc.net
myspaceinc.org
myspacepimpedup.com
myspamless.com
neomailbox.com
nervmich.net
nervtmich.net
netmails.com
netmails.net
netzidiot.de
neverbox.com
nomail.xl.cx
nospam.ze.tc
nurfuerspam.de
objectmail.com
obobbo.com
oneoffemail.com
oopi.org
ordinaryamerican.net
otherinbox.com
ourklips.com
outlawspam.com
pancakemail.com
pimpedupmyspace.com
poofy.org
postalmail.biz
privacy.net
proxymail.eu
punkass.com
putthisinyourspamdatabase.com
pwrby.com
qoika.com
rainmail.biz
rcpt.at
reallymymail.com
recursor.net
regbypass.comsafe-mail.net
rejectmail.com
rhyta.com
rklips.com
safersignup.de
shiftmail.com
shortmail.net
sibmail.com
slaskpost.se
sneakemail.com
solvemail.info
soodonims.com
spambob.com
spamcannon.com
spamcannon.net
spamcon.org
spamcorptastic.com
spamcowboy.com
spamcowboy.net
spamcowboy.org
spamex.com
spamgoes.in
spamgourmet.net
spamgourmet.org
spamhereplease.com
spamoff.de
spamslicer.com
spamtrail.com
speed.1s.fr
superrito.com
tafmail.com
tagyourself.com
temp-mail.com
temp-mail.net
temp-mail.org
temp-mail.ru
teleworm.com
teleworm.us
tempail.com
tempalias.com
tempemail.biz
tempemail.co.za
tempemail.com
tempe-mail.com
tempemail.net
tempinbox.co.uk
tempinbox.com
tempmail.com
temp-mail.com
tempmail.de
temp-mail.de
tempmail.eu
tempmail.info
tempmail.it
tempmail.org
temp-mail.org
temp-mail.ru
tempmail2.com
tempmaildemo.com
tempmailer.com
tempmailer.de
tempomail.fr
temporarily.de
temporarioemail.com.br
temporaryemail.net
temporaryemailid.com
temporaryforwarding.com
temporaryinbox.com
temporarymailaddress.com
thanksnospam.info
thankyou2010.com
thismail.ru
throwawayaddress.com
throwawayemailaddress.com
throwawaymail.com
tilien.com
trash-mail.at
trashmail.de
trashmail.me
trashmail.org
tryalert.com
turual.com
twinmail.de
unmail.ru
upliftnow.com
uplipht.com
venompen.com
viditag.com
viewcastmedia.com
viewcastmedia.net
viewcastmedia.org
vomoto.com
wegwerfadresse.de
wegwerfmail.de
wegwerfmail.net
wegwerfmail.org
wetrainbayarea.com
wetrainbayarea.org
whatpaas.com
winemaven.info
wronghead.com
wuzup.net
wwwnew.eu
xagloo.com
xemaps.com
xents.com
xmaily.com
xoxy.net
yep.it
yogamaven.com
yopmail.fr
yopmail.net
ypmail.webarnak.fr.eu.org
zetmail.com
zoemail.org
qasti.com
qisdo.com
lastmail.co
landmail.co
one-time.email
)